[package]
name = "semvertag-core"
description = "Turn `git describe`-style strings into SemVer versions with intuitive ordering"
keywords = ["semver", "git", "version", "describe"]
categories = ["development-tools", "parser-implementations"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
semver = "1"

[dev-dependencies]
proptest = "1"